apiVersion: apps/v1
kind: Deployment
metadata:
   name: golang-deployment
   labels:
      app: golang
spec:
   replicas: 2
   selector:
      matchLabels:
         app: golang
   template:
      metadata:
         labels:
                 app: golang
      spec:
             containers:
                 - name: golang
                   image: ikhsannugs/golang:versi
                   ports:
                     - name: http
                       containerPort: 8123
---
apiVersion: v1
kind: Service
metadata:
        name: golang-service
spec:
        type: LoadBalancer
        selector:
                app: golang
        ports:
                - protocol: TCP
                  port: 80
                  #protocol: TCP
                  targetPort: 8123
